version: '3.8'

services:
  db:
    image: mariadb:10.5.8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=workstep
      - MYSQL_ROOT_PASSWORD=testProject
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local